In [ ]:
import tensorflow as tf
from tensorflow.keras import layers
import pandas as pd
import numpy as np
from tensorflow.keras import datasets, layers, models
from tensorflow.keras.utils import to_categorical

In [ ]:
df = pd.read_csv('/content/IRIS.csv')
df.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [ ]:
df['species'].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [ ]:
X = df.iloc[:,0:4].values
y = df.iloc[:,4].values

In [ ]:
print(X[0:5])
print(y[0:5])

[[5.1 3.5 1.4 0.2]
 [4.9 3.  1.4 0.2]
 [4.7 3.2 1.3 0.2]
 [4.6 3.1 1.5 0.2]
 [5.  3.6 1.4 0.2]]
['Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa' 'Iris-setosa']


In [ ]:
print(X.shape)
print(y.shape)

(150, 4)
(150,)


In [ ]:
from sklearn.preprocessing import LabelEncoder
encoder =  LabelEncoder()
y1 = encoder.fit_transform(y)

In [ ]:
print(y1)

[0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0
 0 0 0 0 0 0 0 0 0 0 0 0 0 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1
 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 1 2 2 2 2 2 2 2 2 2 2 2
 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2 2
 2 2]


In [ ]:
Y = pd.get_dummies(y1).values
print(Y[0:5])

[[1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]
 [1 0 0]]


In [ ]:
from sklearn.model_selection import train_test_split

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(X, Y, test_size=0.2, random_state=0)

In [ ]:
print(X_train[0:5])

[[6.4 3.1 5.5 1.8]
 [5.4 3.  4.5 1.5]
 [5.2 3.5 1.5 0.2]
 [6.1 3.  4.9 1.8]
 [6.4 2.8 5.6 2.2]]


In [ ]:
print(y_train[0:5])

[[0 0 1]
 [0 1 0]
 [1 0 0]
 [0 0 1]
 [0 0 1]]


In [ ]:
model = tf.keras.Sequential([
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(10, activation='relu'),
    tf.keras.layers.Dense(3, activation='softmax')
  ])
model

In [ ]:
model.compile(optimizer='rmsprop',
              loss='categorical_crossentropy',
              metrics=['accuracy'])

In [ ]:
model.fit(X_train, y_train, batch_size=50, epochs=100)

Epoch 1/100
3/3 [==============================] - 1s 5ms/step - loss: 1.2002 - accuracy: 0.3667
Epoch 2/100
3/3 [==============================] - 0s 5ms/step - loss: 1.0697 - accuracy: 0.3667
Epoch 3/100
3/3 [==============================] - 0s 4ms/step - loss: 1.0114 - accuracy: 0.3667
Epoch 4/100
3/3 [==============================] - 0s 5ms/step - loss: 0.9647 - accuracy: 0.3667
Epoch 5/100
3/3 [==============================] - 0s 5ms/step - loss: 0.9349 - accuracy: 0.3667
Epoch 6/100
3/3 [==============================] - 0s 5ms/step - loss: 0.9103 - accuracy: 0.3750
Epoch 7/100
3/3 [==============================] - 0s 6ms/step - loss: 0.8939 - accuracy: 0.5000
Epoch 8/100
3/3 [==============================] - 0s 5ms/step - loss: 0.8823 - accuracy: 0.5500
Epoch 9/100
3/3 [==============================] - 0s 5ms/step - loss: 0.8698 - accuracy: 0.6167
Epoch 10/100
3/3 [==============================] - 0s 5ms/step - loss: 0.8612 - accuracy: 0.6167
Epoch 11/100
3/3 [===========

In [ ]:
loss, accuracy = model.evaluate(X_test, y_test, verbose=0)
print('Test loss:', loss)
print('Test accuracy:', accuracy)

Test loss: 0.3235296905040741
Test accuracy: 0.9666666388511658


In [ ]:
y_pred = model.predict(X_test)
y_pred

1/1 [==============================] - 0s 68ms/step


array([[1.45905488e-03, 1.57409251e-01, 8.41131687e-01],
       [9.49452370e-02, 7.03248560e-01, 2.01806098e-01],
       [9.79849100e-01, 1.81247983e-02, 2.02600914e-03],
       [2.00069253e-03, 2.84253359e-01, 7.13745952e-01],
       [9.54278290e-01, 4.08090912e-02, 4.91251005e-03],
       [5.20133181e-04, 1.10280186e-01, 8.89199615e-01],
       [9.67186153e-01, 2.91655753e-02, 3.64831765e-03],
       [2.99449004e-02, 6.01340353e-01, 3.68714720e-01],
       [3.32685970e-02, 6.33490145e-01, 3.33241284e-01],
       [6.99995756e-02, 6.64897799e-01, 2.65102714e-01],
       [3.56438337e-03, 2.79960215e-01, 7.16475427e-01],
       [3.04145608e-02, 5.77881992e-01, 3.91703397e-01],
       [2.41188537e-02, 5.45838058e-01, 4.30043072e-01],
       [3.13041545e-02, 5.93749702e-01, 3.74946028e-01],
       [1.85454618e-02, 4.99822080e-01, 4.81632411e-01],
       [9.49075162e-01, 4.56873253e-02, 5.23757329e-03],
       [2.13700216e-02, 5.02180994e-01, 4.76449013e-01],
       [2.27682833e-02, 4.88691

In [ ]:
X_test.shape

(30, 4)

In [ ]:
actual = np.argmax(y_test,axis=1)
predicted = np.argmax(y_pred,axis=1)
print(f"Actual: {actual}")
print(f"Predicted: {predicted}")

Actual: [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 1 0 0 2 0 0 1 1 0]
Predicted: [2 1 0 2 0 2 0 1 1 1 2 1 1 1 1 0 1 1 0 0 2 2 0 0 2 0 0 1 1 0]


In [ ]:
model.save('iris.h5')

/usr/local/lib/python3.10/dist-packages/keras/src/engine/training.py:3103: UserWarning: You are saving your model as an HDF5 file via `model.save()`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')`.
  saving_api.save_model(


In [ ]:
from keras.models import load_model
model = load_model('/content/iris.h5')

input_values = np.array([[0.9, 0.9, 0.9, 0.5]])

predictions = model.predict(input_values)

# Print predicted class
print(np.argmax(predictions))

1/1 [==============================] - 0s 237ms/step
1
